services:
  mongo:
    image: mongo:latest
    container_name: mongo-vehicle-resale-auth
    restart: on-failure
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data_vehicle_resale_auth:/data/db

volumes:
  mongo_data_vehicle_resale_auth:
