name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./... -v -short

  # integration-tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
  #   needs: unit-tests

  #   services:
  #     mongo:
  #       image: mongo:6
  #       ports:
  #         - 27017:27017
  #       env:
  #         MONGO_INITDB_ROOT_USERNAME: test
  #         MONGO_INITDB_ROOT_PASSWORD: test
  #       options: >-
  #         --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
  #         --health-interval=10s
  #         --health-timeout=5s
  #         --health-retries=5

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: "1.25.2"

  #     - name: Download dependencies
  #       run: go mod download

  #     - name: Wait for MongoDB
  #       run: |
  #         for i in {1..10}; do
  #           nc -z localhost 27017 && echo "MongoDB is up!" && break
  #           echo "Waiting for MongoDB..."
  #           sleep 3
  #         done

  #     - name: Run integration tests
  #       run: go test ./tests -v -tags=integration
